# Generated by Django 4.1.1 on 2022-09-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTaxe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='loan',
            field=models.IntegerField(null=True),
        ),
    ]
